name: Assignees4label
on:
  issues:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:
  set-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set assignees from labels
        uses: kyanagimoto/assignee4label@main   # better: pin to a release tag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/assignee4label.yml
