name: Inherit Issue Labels

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  copy-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Copy labels from linked issue (body)
        uses: michalvankodev/copy-issue-labels@v1.2.1
        with:
          repo-token: ${{ github.token }}
          custom-keywords: 'fixes|closes|resolves|refs|addresses'

      - name: Copy labels from linked issue (title)
        uses: michalvankodev/copy-issue-labels@v1.2.1
        with:
          repo-token: ${{ github.token }}
          from-title: true
          custom-keywords: 'fixes|closes|resolves|refs|addresses'
