# .github/workflows/copy-issue-label-to-linked-pr.yml
name: Copy issue label to linked PRs (wait for link)

on:
  issues:
    types: [labeled]   # add 'unlabeled' later if you also want to remove from PRs

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for a linked PR, then mirror the label
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const {owner, repo} = context.repo
            const issue_number = context.payload.issue.number
            const label = context.payload.label.name

            // Helper: fetch PRs linked to this issue (covers sidebar link + "Fixes #X")
            async function findLinkedPRs() {
              const events = await github.paginate(
                github.rest.issues.listEventsForTimeline,
                {
                  owner, repo, issue_number, per_page: 100,
                  mediaType: { previews: ['mockingbird'] } // timeline API
                }
              )
              const prs = [...new Set(
                events
                  .filter(e =>
                    (e.event === 'connected' || e.event === 'cross-referenced') &&
                    e.source?.issue?.pull_request
                  )
                  .map(e => e.source.issue.number)
              )]
              return prs
            }

            // Poll for up to 10 minutes until a PR is linked
            const deadline = Date.now() + 10 * 60 * 1000
            let prs = await findLinkedPRs()
            while (prs.length === 0 && Date.now() < deadline) {
              core.info('No linked PR yet; waiting 20s…')
              await new Promise(r => setTimeout(r, 20_000))
              prs = await findLinkedPRs()
            }

            if (prs.length === 0) {
              core.info('No linked PR found before timeout. Exiting gracefully.')
              return
            }

            for (const pr of prs) {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: pr, labels: [label]
              })
              core.info(`Added "${label}" to PR #${pr}`)
            }
