# .github/workflows/copy-issue-label-to-linked-pr.yml
name: Copy issue label to linked PRs

on:
  issues:
    types: [labeled]   # add 'unlabeled' if you also want to remove it from PRs

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  push-label:
    if: ${{ github.event.label.name == 'question' }}
    runs-on: ubuntu-latest
    steps:
      - name: Add label to linked PRs
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const {owner, repo} = context.repo
            const issue_number = context.payload.issue.number
            const label = context.payload.label.name

            // Get timeline to find linked PRs (covers sidebar "linked" and body references)
            const events = await github.paginate(
              github.rest.issues.listEventsForTimeline,
              {
                owner, repo, issue_number, per_page: 100,
                mediaType: { previews: ['mockingbird'] } // required for timeline
              }
            )

            const prs = [...new Set(
              events
                .filter(e =>
                  (e.event === 'connected' || e.event === 'cross-referenced') &&
                  e.source?.issue?.pull_request
                )
                .map(e => e.source.issue.number)
            )]

            if (prs.length === 0) {
              core.info('No linked PRs found.')
              return
            }

            for (const pr of prs) {
              await github.rest.issues.addLabels({
                owner, repo, issue_number: pr, labels: [label]
              })
              core.info(`Added "${label}" to PR #${pr}`)
            }
